###

GET http://localhost:3000/api/employees HTTP/1.1

###

POST http://localhost:3000/api/employees HTTP/1.1
Content-Type: application/json

{
    "identif": "abcd1234",
    "fullName": "Nombre Prueba Prueba",
    "email": "direccionprueba@gmail.com",
    "usernamePassword": "nombreprueb1234567"
}

### 

GET http://localhost:3000/api/employees/5f8984c316beaf3248370e20 HTTP/1.1

###

PUT http://localhost:3000/api/employees/5f8984c316beaf3248370e20
Content-Type: application/json

{
    "identif": "defg5678",
    "fullName": "Nombre2 Prueba2 Prueba2",
    "email": "direccionprueba2@gmail.com",
    "usrernamePassword": "userPassword"
}

###
DELETE http://localhost:3000/api/employees/5f8984c316beaf3248370e20
